### PR TITLE
[master] feat: added possibility to add a user-defined global defaults, from the pilot options

### PR DESCRIPTION
**Pull request by fstagni**
solves #113 

@zhangxiaomei Have a look, IIUC this is what you want

- [ ] port it to `management` repo if approved.

### CODE REVIEW

**Comment by zhangxiaomei** [comment]
Looks fine to us, thanks.

**Comment by fstagni** [comment]
@atsareg review?

**Comment by zhangxiaomei** [comment]
Look at again and have one question:
I haven't seen user_globalDefaultsURL was used here.  The logic I saw is: first look at globalDefaultsCVMFSPath -> If not available, go to use diracproject.web.cern.ch -> If not available, return

**Comment by atsareg** [comment]
I do not see where global defaults are loaded from self.user_globalDefaultsURL in dirac-install.py. Wasn't it forgotten ?

**Comment by fstagni** [comment]
> Look at again and have one question:
> I haven't seen user_globalDefaultsURL was used here. The logic I saw is: first look at globalDefaultsCVMFSPath -> If not available, go to use diracproject.web.cern.ch -> If not available, return

`user_globalDefaultsURL` is used, when requested, instead of `globalDefaultsCVMFSPath`. If `user_globalDefaultsURL` is not defined, and `globalDefaultsCVMFSPath` is not reachable, it will use diracproject.web.cern.ch. 

> I do not see where global defaults are loaded from self.user_globalDefaultsURL in dirac-install.py. Wasn't it forgotten ?

Ah right. It should be better now.

**Review by zhangxiaomei — APPROVED** [review]

**Pull request merged**
