### PR TITLE
[master] Setting up preinstalled DIRAC in a pilot

### PR DESCRIPTION
**Pull request by atsareg**
This PR allows to specify the setup script location which will be used to define a preinstalled DIRAC environment instead of installing DIRACOS2/DIRAC from scratch on a worker node. Example script locations:

   - /cvmfs/dirac.egi.eu/dirac/pro/diracos/diracosrc
   - /cvmfs/dirac.egi.eu/dirac/bashrc_egi

  This is addressing #166 but makes use of predefined DIRAC clients in CVMFS.

### CODE REVIEW

**Comment by fstagni** [comment]
This is a bit different/simpler solution to #166 , the question here if this would be enough. 
Using a `venv`, as suggested in the original issue, would add flexibility on top of what is here.

**Comment by chrisburr** [comment]
This effectively bypasses the pilot version specified in the CS which doesn't feel great. It also doesn't work if you have multiple architectures. If we could instead have a layout like:

```bash
/cvmfs/dirac.egi.eu/dirac/{version}/{uname -m}-{uname -s}/diracosrc
```

You can then have `--preinstalledEnvPrefix=/cvmfs/dirac.egi.eu/dirac/` and would probably be good enough to replace the `LHCbInstallDIRAC` pilot command.

**Comment by atsareg** [comment]
In CVMFS we have now /cvmfs/dirac.egi.eu/dirac/{version}/diracos/diracosrc. So a particular DIRAC version can be specified. But not different platforms. In LHCb you have different platforms installed in cvmfs ?

**Comment by chrisburr** [comment]
I'd propose having `--preinstalledEnvBashrc=` in addition to `--preinstalledEnvPrefix=/cvmfs/dirac.egi.eu/dirac/` with the view that it contains at least something like:

```
source ${DIRACOS}/diracosrc
```

**Comment by atsareg** [comment]
The PR is updated along the lines of the discussion above. I keep to settings, --preinstalledEnv and --preinstalledEnvPrefix. If --preinstalledEnv is specified, it is used as the environment setting script, --preinstalledEnvPrefix is ignored in that case. If --preinstalledEnvPrefix is specified  (and not  --preinstalledEnv), then environment is resolved with the release area structure like in the CVMFS of LHCb. I have updated the /cvmfs/dirac.egi.eu to this structure already

**Comment by fstagni** [comment]
One more note: the case of user-defined environments is not considered in this implementation.

**Comment by fstagni** [comment]
Closing as superseded by #205

**Pull request closed without merging**
