### PR TITLE
Change the jenkins test file to point to default repo

### PR DESCRIPTION
**Pull request by wkrzemien**

### CODE REVIEW

**Comment by fstagni** [comment]
My idea was to remove this file.

**Comment by wkrzemien** [comment]
@fstagni the current jenikns file points to master and has  PilotLogger flag off. This what is added points to devel with the pilotLogger option on. I think haveing to setups for master and devel are ok?

**Comment by wkrzemien** [comment]
Also, DIRAC version can be different

**Comment by fstagni** [comment]
Fine, but this is just changing the defaults, nothing more than that.

**Comment by wkrzemien** [comment]
@fstagni I hope now is fine

**Comment by fstagni** [comment]
Thanks!

**Comment by wkrzemien** [comment]
@fstagni Do you think you can merge it?

**Pull request merged**
