### PR TITLE
feat: support multi-core allocations to compute cpu power

### PR DESCRIPTION
**Pull request by aldbr**
Need this PR to be merged before: https://github.com/DIRACGrid/DIRAC/pull/5939

Passing the number of processors available in the allocation to `dirac-wms-get-cpu-normalization`.

### CODE REVIEW

**Comment by fstagni** [comment]
If we merge this PR before the DIRAC one, we'll get into

```
# dirac-wms-cpu-normalization --NumberOfProcessors=3
Error when parsing command line arguments: option --NumberOfProcessors not recognized
```
and if we merge it after, we'll get anyway in this same situation because of users/installations installing older versions of DIRAC.

**Comment by fstagni** [comment]
It is MAYBE possible to extract the script from DIRAC and add it here, but I think it is more realistic a (ugly) "try with `--NumberOfProcessors` option and remove it if it fails"

**Comment by aldbr** [comment]
> and if we merge it after, we'll get anyway in this same situation because of users/installations installing older versions of DIRAC.

Oops yes indeed...

> It is MAYBE possible to extract the script from DIRAC and add it here, but I think it is more realistic a (ugly) "try with `--NumberOfProcessors` option and remove it if it fails"

Yes, the second solution seems easier but ugly...

What if:
- I remove the `NumberOfProcessors` argument from `dirac-wms-cpu-normalization`
- `dirac-wms-cpu-normalization` directly gets `numberOfProcessors` from the configuration that we pass?

**Comment by fstagni** [comment]
> What if:
> 
>     * I remove the `NumberOfProcessors` argument from `dirac-wms-cpu-normalization`
> 
>     * `dirac-wms-cpu-normalization` directly gets `numberOfProcessors` from the configuration that we pass?


Looks reasonable. You can get it from `/Resources/Computing/CEDefaults/NumberOfProcessors`

**Comment by aldbr** [comment]
Closing this PR.
The following PR should be enough to support multi-core DB12: https://github.com/DIRACGrid/DIRAC/pull/5939
It tries to get the number of processors from the CLI first, and then from the `cfg` file.

**Pull request closed without merging**
